---

- name: Add helm apt key.
  ansible.builtin.apt_key:
    url: "{{ helm_apt_key }}"
    state: "{{ helm_state }}"

- name: Add helm apt repository.
  ansible.builtin.apt_repository:
    repo: "{{ helm_apt_repository_string }}"
    state: "{{ helm_state }}"
    update_cache: true

- name: Ensure helm is installed
  ansible.builtin.apt:
    name: "helm"
    state: "{{ helm_state }}"
    update_cache: true
