---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ensure_helm_state
    image: python:bullseye
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
