---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check Helm version.
      ansible.builtin.command: "helm version"
      changed_when: false
      register: helm_verify_version

    - name: Verify Helm's version is installed.
      ansible.builtin.assert:
        that:
          - helm_verify_version.stdout is search('3')